# syntax=docker/dockerfile-upstream:1.4.0
FROM --platform=linux/amd64 debian:bullseye-slim

# PORTER_INIT

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

# Git is required for terraform_azurerm_environment_configuration
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt \
  apt-get update && apt-get install -y git jq curl ca-certificates patch --no-install-recommends

WORKDIR ${BUNDLE_DIR}

# copy files from the base workspace (dir passed to porter via --build-context)
# ignoring hadolint DL3022; for details see https://github.com/hadolint/hadolint/issues/830
#
# hadolint ignore=DL3022
COPY --from=base --link . ${BUNDLE_DIR}/

# Copy and change the file extension of .terraform file to .tf
COPY ./terraform/research-variables.terraform "${BUNDLE_DIR}"/terraform/research-variables.tf
COPY ./terraform/research-workspace.terraform "${BUNDLE_DIR}"/terraform/research-workspace.tf
COPY ./terraform/research-adf/adf.terraform "${BUNDLE_DIR}"/terraform/research-adf/adf.tf
COPY ./terraform/research-adf/locals.terraform "${BUNDLE_DIR}"/terraform/research-adf/locals.tf
COPY ./terraform/research-adf/providers.terraform "${BUNDLE_DIR}"/terraform/research-adf/providers.tf
COPY ./terraform/research-adf/storage.terraform "${BUNDLE_DIR}"/terraform/research-adf/storage.tf
COPY ./terraform/research-adf/variables.terraform "${BUNDLE_DIR}"/terraform/research-adf/variables.tf
COPY ./terraform/network/security-nwsde.terraform "${BUNDLE_DIR}"/terraform/network/security-nwsde.tf
COPY ./terraform/aad/aad_override.terraform "${BUNDLE_DIR}"/terraform/aad/aad_override.tf

# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY --link . ${BUNDLE_DIR}/
