# syntax=docker/dockerfile-upstream:1.4.0
FROM --platform=linux/amd64 debian:bullseye-slim

# PORTER_INIT

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

# Git is required for terraform_azurerm_environment_configuration
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt \
  apt-get update && apt-get install -y git jq curl ca-certificates patch --no-install-recommends

ARG AZURE_TRE_VERSION="0.17.0"

WORKDIR ${BUNDLE_DIR}

# Copy all files from base workspace (note: some of them will be overwritten with the following COPY command)
RUN curl -o azuretre.tar.gz -L "https://github.com/microsoft/AzureTRE/archive/refs/tags/v${AZURE_TRE_VERSION}.tar.gz" \
  && tar -xzf azuretre.tar.gz "AzureTRE-${AZURE_TRE_VERSION}/templates/workspaces/base" --strip-components=4 --skip-old-files \
  && rm -rf azuretre.tar.gz

# Copy and change the file extension of .terraform file to .tf
COPY ./terraform/research-storage.terraform "${BUNDLE_DIR}"/terraform/research-storage.tf
COPY ./terraform/research-variables.terraform "${BUNDLE_DIR}"/terraform/research-variables.tf
COPY ./terraform/research-workspace.terraform "${BUNDLE_DIR}"/terraform/research-workspace.tf
COPY ./terraform/research-adf/research-adf.terraform "${BUNDLE_DIR}"/terraform/research-adf/research-adf.tf
COPY ./terraform/research-adf/research-data.terraform "${BUNDLE_DIR}"/terraform/research-adf/research-data.tf
COPY ./terraform/research-adf/research-locals.terraform "${BUNDLE_DIR}"/terraform/research-adf/research-locals.tf
COPY ./terraform/research-adf/research-providers.terraform "${BUNDLE_DIR}"/terraform/research-adf/research-providers.tf
COPY ./terraform/research-adf/research-variables.terraform "${BUNDLE_DIR}"/terraform/research-adf/research-variables.tf

# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY --link . ${BUNDLE_DIR}/
